# Generated by Django 6.0.6 on 2026-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hospital', models.CharField(default='Hospital SENAI', max_length=100, verbose_name='Nome do Hospital')),
                ('subtitulo', models.CharField(default='Sistema Integrado de Triagem e Atendimento Médico', max_length=200, verbose_name='Subtítulo Institucional')),
                ('titulo_documento', models.CharField(default='Receita Médica', max_length=100, verbose_name='Título do Documento')),
                ('subtitulo_documento', models.CharField(default='Uso Médico e Farmacêutico', max_length=100, verbose_name='Subtítulo do Documento')),
                ('local_emissao', models.CharField(default='São Paulo', max_length=100, verbose_name='Cidade / Estado de Emissão')),
                ('rodape_legal', models.CharField(default='Receita gerada eletronicamente através do Sistema de Triagem Hospitalar SENAI', max_length=255, verbose_name='Texto do Rodapé Legal')),
            ],
            options={
                'verbose_name': 'Configuração do Hospital',
                'verbose_name_plural': 'Configuração do Hospital',
            },
        ),
    ]
