# Generated by Django 6.0.6 on 2026-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=20)),
                ('prioridade', models.CharField(max_length=20)),
                ('tempo_max_atendimento', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(db_index=True, max_length=15, unique=True)),
                ('coren', models.CharField(max_length=20, unique=True)),
                ('telefone', models.TextField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(db_index=True, max_length=15, unique=True)),
                ('CRM', models.CharField(max_length=6, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('especialidade', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('sobrenome', models.CharField(max_length=32)),
                ('cpf', models.CharField(db_index=True, max_length=15, unique=True)),
                ('data_nascimento', models.DateField()),
                ('numero_telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
