# Generated by Django 6.0.6 on 2026-06-19 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_triagem', models.DateField(auto_now_add=True)),
                ('peso', models.FloatField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressao_arterial', models.CharField(max_length=20)),
                ('saturacao', models.IntegerField()),
                ('sintomas', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('classificacao_risco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.classificacaorisco')),
                ('enfermeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.enfermeiro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateField(auto_now=True)),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('diagnostico', models.TextField()),
                ('prescricao', models.TextField()),
                ('medicos', models.ManyToManyField(to='cadastro.medico')),
                ('triagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triagem.triagem')),
            ],
        ),
    ]
