# Generated by Django 6.0.6 on 2026-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='alergias',
            field=models.TextField(blank=True, default='', verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='doencas_deficiencias',
            field=models.TextField(blank=True, default='', verbose_name='Doenças ou Deficiências'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='utilizou_drogas',
            field=models.BooleanField(default=False, verbose_name='Utilizou álcool ou drogas?'),
        ),
    ]
